### ISSUE TITLE
https://wiki.kiwix.org/wiki/Content_in_all_languages not displaying as template size limit is exceeded.

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#153]
As it is a duplicate, should we not just redirect to library.kiwix.org instead of fixing the template issue?

**Comment by kelson42** [comment]
Would like to integrate a widget exported from library.kiwix.org.

**Comment by kelson42** [comment]
@rgaudin Somehow something has changed:
* The upload content is really bigger, see https://wiki.kiwix.org/w/index.php?title=Template:ZIMdumps/content&action=history
* Is not updated anymore one a day
* Not with the `librarybot` user

If the increase of size is legitimate, then we should allow larger articles, maybe with https://www.mediawiki.org/wiki/Manual:$wgMaxArticleSize

**Comment by rgaudin** [comment]
> @rgaudin Somehow something has changed:

It's not "somehow", it's been "ported" to the new script

> * The upload content is really bigger, see https://wiki.kiwix.org/w/index.php?title=Template:ZIMdumps/content&action=history

15% bigger if I recall properly (can't check at the
moment)

> * Is not updated anymore one a day

No, it's supposed to be every hour now which should not be a problem since the diff would be zero or small most of the time. the pylibzim bug creates noise here as we have the two scripts running.

> * Not with the `librarybot` user

It's on purpose. It's login method was deprecated so I followed the bot user recommended way to prevent a future breakage and remove the warning.
>
> If the increase of size is legitimate, then we should allow larger articles, maybe with https://www.mediawiki.org/wiki/Manual:$wgMaxArticleSize

It is. The differences are two fold:
- a couple of spaces in wiki code around table cells that makes maintenance easier (over 4,000 rows that's a few dozen KiB.
- language names are now present. Previous script had a limited map of language names and fallback to lang code. Now we have all (or most) language names. That's the biggest increase.
- Sizes use the default output of human friendly which is up to 2 decimals as well as proper unit while it was rounded and with an unclear "M". So "2M" can be "1.94MB" now.

I'll update that variable. I missed that page
in the template's Articles using it section

**Comment by rgaudin** [comment]
Fixed
