### ISSUE TITLE
SEO Fixes - Remove duplicate H1 tags from the pages

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#184]
List Duplicate H1 tags URL - https://docs.google.com/spreadsheets/d/1umdRck7NEblrFVENF6BFidMjDNQukRvALQ8inHNzZgE/edit#gid=2063773708

Description:
It's important to have distinct, unique and useful main headings. If every page has the same, then it can make it more challenging for users and the search engines to understand one page from another. Identical headings on pages with different content imply that the headings don’t uniquely describe the specific content on each page.

Resolution:
- Edit or rewrite h1 tags so that they specifically match the content of the pages they belong to so important pages contain a unique and descriptive for users and search engines.
- If these are duplicate pages, then fix the duplicated pages by linking to a single version, and redirect or use canonicals where appropriate.

**Comment by Popolechien** [comment]
@svikrantaxioned Not sure I understand your recommendation: we should rewrite the H1 title so that it is different from the page title? (see below for https://www.kiwix.org/en/downloads/kiwix-custom-apps/)
Current:
![Capture d’écran 2023-02-09 à 16 26 35](https://user-images.githubusercontent.com/21675885/217857122-4de1edff-8da1-4918-9f4a-263adebd665d.png)
Proposed correction:
![Capture d’écran 2023-02-09 à 16 27 44](https://user-images.githubusercontent.com/21675885/217857131-330928b1-2565-4208-8737-508d288eb4c7.png)

**Comment by svikrantaxioned** [comment]
@Popolechien The page title should not be different from the H1. The Urls mentioned in the sheet have duplicate H1 tags i.e. they have identical headings with different content on some other page

**Comment by kelson42** [comment]
@Popolechien I understand the problem in case this is still unclear to you. To me the section headings shoukd simply be translated (if a good idea at all).

**Comment by Popolechien** [comment]
Fixed.
