### ISSUE TITLE
Unable to download the free kiwix-hotspot image

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#198]
from https://www.kiwix.org/en/cardshop-access/.

If I click on the "download" button, I get an error

**Comment by kelson42** [comment]
https://cardshop.hotspot.kiwix.org/health-check has the explanation

**Comment by rgaudin** [comment]
Fixed. Here's what happened:

- on Feb 1st the auto regeneration of the `demo` auto-image failed because one of it's ZIM had been removed from the catalog.
- @Popolechien had to change the config and recreate.
- I believe he deleted the autoimage and recreated it but accidentally marking it as private (`demo` is the only non-private auto-image)
