### ISSUE TITLE
wiki.kiwix.org is down

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#70]
And so is library.kiwix.org (502 Bad Gateway)

For the wiki I get the below message:
``MediaWiki internal error.``

``Original exception: [3a131cf70f9d2858bbc7727f] 2019-07-10 15:53:32: Fatal exception of type "Wikimedia\Rdbms\DBQueryError"``

``Exception caught inside exception handler.``

``Set $wgShowExceptionDetails = true; and $wgShowDBErrorBacktrace = true; at the bottom of LocalSettings.php to show detailed debugging information.``

**Comment by kelson42** [comment]
We have already bugs open for library.kiwix.org: the problem is know and quite on the top of our prio list.
The problem with the wiki is different. For some reason the DB seems to die time to time. So, the problem is sporadic and seems to happen around one/two times a month. I have restarted the serivice and increase the memory available by 200MB. Hope this will help to fix the problem.
